CREATE TABLE IF NOT EXISTS user(
Id INT AUTO_INCREMENET PRIMARY KEY NOT NULL,
Username VARCHAR(20) NOT NULL,
Password VARCHAR(200) NOT NULL,
Email VARCHAR(35) NOT NULL,
Age INT NOT NULL,
Is_admin BOOLEAN DEFAULT FALSE,
Is_supplier BOOLEAN DEFAULT FALSE
);

